### ISSUE TITLE
Usage of corrupted package build

### ISSUE THREAD

**Issue by serathius** [paylogic/pip-accel#38]
During building celery, occurred error:
```
2014-11-13 11:23:46 ns3314108.ovh.net pip_accel.bdist[12645] INFO Building binary distribution of celery (3.1.16) ..
2014-11-13 11:23:47 ns3314108.ovh.net pip_accel.bdist[12645] INFO Finished building celery (3.1.16) in 1.31 second.
Traceback (most recent call last):
  File "/tmp/test-virtualenv/bin/pip-accel", line 9, in <module>
    load_entry_point('pip-accel==0.14.1', 'console_scripts', 'pip-accel')()
  File "/tmp/test-virtualenv/lib/python3.3/site-packages/pip_accel/__init__.py", line 121, in main
    install_requirements(requirements, cache)
  File "/tmp/test-virtualenv/lib/python3.3/site-packages/pip_accel/__init__.py", line 285, in install_requirements
    install_binary_dist(members, prefix=install_prefix, python=python)
  File "/tmp/test-virtualenv/lib/python3.3/site-packages/pip_accel/bdist.py", line 247, in install_binary_dist
    for member, from_handle in members:
  File "/tmp/test-virtualenv/lib/python3.3/site-packages/pip_accel/bdist.py", line 91, in get_binary_dist
    with open(transformed_file, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/celery-3.1.16.linux-x86_64.tar'
```
This error didn't stop pip-accel from using not built version of celery, and caused celery package to missfunction. Only way to fix this for that version of celery is manually deletion of that celery build.

In my opinion manual fixing shouldn't be required for every error that occurs during building packages.
Additionally tmp folder doesn't guarantee file persistence event between two shell commands, so opening of temporary files should be better handled.

**Comment by xolox** [comment]
Without follow up from @serathius I don't know what I should be fixing here and I asked for details quite a while ago but never got any, so there's no way for me to resolve the problem (whatever it is). This is why I'm going to go ahead and close this issue. If @serathius feels like following up here by answering my questions then please feel free to reopen this issue.
